package gui

func authors() []string {
	return []string{
		"Adam Langley",
		"Bruce Leidl  -  bruce@subgraph.com",
		"CodeLingo Bot  -  bot@codelingo.io",
		"Cody Zacharias  -  22013186+haccer@users.noreply.github.com",
		"Cristian Naranjo  -  mauro.velasco@gmail.com",
		"Cristina Muñoz  -  hi@xmunoz.com",
		"Fan Jiang  -  fan.torchz@gmail.com",
		"Giovane Liberato  -  giovane@riseup.net",
		"Gray Leonard  -  gl7039a@american.edu",
		"Ivan Jijon  -  ivanjijon@autonomia.digital",
		"Ivan Markin  -  twim@riseup.net",
		"Iván Pazmiño  -  iapazmino@gmail.com",
		"Jonathan Reyes  -  j@jreyes.org",
		"Kevin Gallagher  -  kevingallagher@gmail.com",
		"Mauro Velasco  -  mauro.velasco@gmail.com",
		"Ola Bini  -  ola@olabini.se",
		"Pedro Palau  -  pepalauisaac@gmail.com",
		"Ray Tung  -  rtung@thoughtworks.com",
		"Reinaldo Mendoza  -  rmendoza83@gmail.com",
		"Reinaldo de Souza Junior  -  juniorz@gmail.com",
		"Rosalie Tolentino  -  rtolenti@thoughtworks.com",
		"Sandy Acurio  -  sandy.acurio@gmail.com",
		"Santhosh  -  santhosh@autonomia.digital",
		"Sascha Steinbiss  -  sascha@steinbiss.name",
		"Silke Meyer  -  silke@silkemeyer.net",
		"Sofía Celi  -  cherenkovd69@gmail.com",
		"Tania Silva  -  tsilva@thoughtworks.com",
		"Tulio Casagrande  -  tuliocasagrande@gmail.com",
		"Varac  -  varac@leap.se",
		"Yakira Dixon  -  ydixon@thoughtworks.com",
		"pixelrust  -  pixelrust@users.noreply.github.com",
		"reginazabo  -  reginazabo@anche.no",
		"xSmurf  -  xsmurf+github@smurfturf.net",
	}
}
