#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 bundle-dir"
    echo "  example: $0 /tmp/MyApp.app"
    exit 1
fi

set -xe

OUTPUT=$1

frameworks=$OUTPUT/Contents/F
resources=$OUTPUT/Contents/Resources
macos=$OUTPUT/Contents/MacOS
wrapper=$macos/Coy
binary=${wrapper}-bin
cellar=$(brew --prefix)/Cellar

rm -rf $OUTPUT
mkdir -p $macos $frameworks $resources

cp -av bin/coyim $binary
cp -av build/mac-bundle/coyim-launcher.sh $wrapper
cp -av build/mac-bundle/Info.plist $OUTPUT/Contents/Info.plist
cp -av build/mac-bundle/coy.icns $resources

chmod a+x $wrapper $binary

rewrite_library() {
  for lib in $(otool -L $1 | grep "^\t$(brew --prefix)" | sed -e 's/^[^\/]*//' -e 's/ .*//'); do
    base=$(basename $lib)
    if [ ! -f $frameworks/$base ] ; then
      cp $lib $frameworks
    fi
    chmod u+w $1
    install_name_tool -change $lib @executable_path/../F/$base $1
    if [ $(basename $1) != $base ] ; then
      rewrite_library $frameworks/$base
    fi
  done
}

for lib in $(otool -L $binary | grep "^\t$(brew --prefix)" | sed -e 's/^[^\/]*//' -e 's/ .*//'); do
  base=$(basename $lib)
  cp $lib $frameworks
  install_name_tool -change $lib @executable_path/../F/$base $binary
  rewrite_library $frameworks/$base
done

pango_lib=$(strings $frameworks/libpango-1.0.0.dylib  | grep usr/local | grep lib)
cp -a $(dirname $pango_lib) $resources

# There is no pango modules anymore
#pango_etc=$(strings $frameworks/libpango-1.0.0.dylib  | grep usr/local | grep etc)
#cp -a $(dirname $pango_etc) $resources
#sed -i".bak" -e 's![^ ]*/\([^/ ]*\) !\1 !' $(find $resources -name pango.modules)

## Add support to PNG pixbuf. We wont need it until we use images in the app
## this is $(pkg-config --variable=gdk_pixbuf_binarydir gdk-pixbuf-2.0) without $(brew prefix)
#mkdir -p $resources/lib/gdk-pixbuf-2.0/2.10.0
#cat > $resources/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache << EOF
#"../F/libpixbufloader-png.so"
#"png" 5 "gdk-pixbuf" "The PNG image format" "LGPL"
#"image/png" ""
#"png" ""
#"\211PNG\r\n\032\n" "" 100
#EOF
#
#cp $(find $cellar/gdk-pixbuf -name libpixbufloader-png.so | head -n 1) $frameworks
#rewrite_library $frameworks/libpixbufloader-png.so
#
#mkdir -p $resources/share/locale
#for dir in $(find $cellar -name locale -type d); do
#  cp -a $dir/* $resources/share/locale
#done

# Remove all non en locales
#(
#  cd $resources/share/locale
#  find . ! -path . -type d -maxdepth 1 | grep -v '^\./en' | xargs rm -Rf
#)

mkdir -p $resources/etc/gtk-3.0
mkdir -p $resources/share/themes

# We might need this, but not now
#for lib in $(ls -1 $frameworks); do
#    ../pathrewrite/pathrewrite $frameworks/$lib
#  done
#done

