mkdir %GOPATH%\src\github.com\coyim\coyim\release\
mkdir %GOPATH%\src\github.com\coyim\coyim\release\share
mkdir %GOPATH%\src\github.com\coyim\coyim\release\lib

set LIBDIR="/mingw%MSYS2_BITS%/bin"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libatk-1.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libbz2-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libbrotlidec.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libcairo-2.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libcairo-gobject-2.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libdatrie-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libepoxy-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libexpat-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libffi-*.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libfontconfig-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libfreetype-6.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libfribidi-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgcc_s_seh-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgdk_pixbuf-2.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgdk-3-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgio-2.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libglib-2.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgmodule-2.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgobject-2.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgraphite2.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libgtk-3-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libharfbuzz-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libiconv-2.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libintl-8.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libjpeg-8.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpango-1.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpangocairo-1.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpangoft2-1.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpangowin32-1.0-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpcre-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpixman-1-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libpng16-16.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/librsvg-2-2.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libstdc++-6.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libthai-0.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libtiff-5.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libtiffxx-5.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libturbojpeg.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/libwinpthread-1.dll /c/gopath/src/github.com/coyim/coyim/release/"
%MSYS_PATH%\usr\bin\bash -lc "cp -v %LIBDIR%/zlib1.dll /c/gopath/src/github.com/coyim/coyim/release/"

%MSYS_PATH%\usr\bin\bash -lc "cp -r -v /mingw%MSYS2_BITS%/lib/gdk-pixbuf-2.0 /c/gopath/src/github.com/coyim/coyim/release/lib"
%MSYS_PATH%\usr\bin\bash -lc "cp -r /mingw%MSYS2_BITS%/share/icons /c/gopath/src/github.com/coyim/coyim/release/share/"
%MSYS_PATH%\usr\bin\bash -lc "cp -r /mingw%MSYS2_BITS%/share/glib-2.0 /c/gopath/src/github.com/coyim/coyim/release/share/"
%MSYS_PATH%\usr\bin\bash -lc "pacman --noconfirm --needed -Sy sed" > nul
%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim && ci/release"
%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim/release && ls -alF ."
%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim/release && 7z a -tzip coyim.zip *"
%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim/release && rm *.dll"
%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim/release && rm *.exe"
xcopy %GOPATH%\src\github.com\coyim\coyim\release\coyim.zip %APPVEYOR_BUILD_FOLDER%\ /e /i > nul
