#!/bin/bash

set -x

sudo apt-get update -qq
sudo apt-get install -qq -y libgtk-3-dev
sudo apt-get install -qq -y xvfb
sudo /usr/bin/Xvfb $DISPLAY 2>&1 > /dev/null &

sudo apt-get install -qq -y python-dogtail
sudo pip install --upgrade pip
sudo pip install behave
