#!/bin/bash

set -x

# We could build on any GTK+3 version we want
# brew tap coyim/gtk-versions

# ls -alF /usr/local/opt
# ls -alF /usr/local/opt/libffi/
# find /usr/local/opt/libffi/ -name '*.pc'

#/usr/local/opt/libffi/lib/pkgconfig/

time brew update
brew analytics off || true
for dep in gtk+3 gettext adwaita-icon-theme hicolor-icon-theme shared-mime-info libffi gtk-mac-integration create-dmg fileicon pkg-config; do
	time (brew install $dep || brew outdated $dep || brew upgrade $dep)
done
#time brew cleanup || true
