#!/bin/bash

set -x

# We could build on any GTK+3 version we want
# brew tap coyim/gtk-versions

time brew update
brew analytics off || true
for dep in gtk+3 gettext adwaita-icon-theme hicolor-icon-theme shared-mime-info libffi; do
	time (brew install $dep || brew outdated $dep || brew upgrade $dep)
done
time brew cleanup || true
