#!/bin/bash

set -x

# We could build on any GTK+3 version we want
# brew tap twstrike/gtk-versions

brew update
for dep in gtk+3 gettext gnome-icon-theme hicolor-icon-theme; do
   brew install $dep || brew outdated $dep || brew upgrade $dep
done

