#!/bin/bash

set -xe

# We can deploy only when a tag is pushed, and use ir as the version
VERSION="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:7}"
OS=${TRAVIS_OS_NAME:-linux}

[[ $OS = "linux" ]] && make cross-compile
if [[ $OS = "osx" ]]; then
  make build-gui

  # gettext is not linked on OSX
  export PATH="$PATH:$(brew --prefix gettext)/bin"
  make i18n

  iconutil -c icns -o build/mac-bundle/coy.icns build/mac-bundle/coy.iconset

	ci/build-osx-bundle bin/mac-bundle/CoyIM.app

  ln -s /Applications bin/mac-bundle/Applications
  cp build/mac-bundle/ds-store bin/mac-bundle/.DS_Store 

  ci/make-dmg coyim $VERSION bin/mac-bundle/

  rm -rf bin/mac-bundle
fi

make release-gui

# update version on bintray conf file
sed -i".bak" "s <VERSION> $VERSION g" ci/bintray.json


